CREATE TABLE "job_titles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid,
  "name" varchar(100),
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "departaments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid,
  "name" varchar(100),
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid,
  "name" varchar(100),
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "clients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid,
  "name" varchar(100),
  "email" varchar(100),
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" integer,
  "job_title_id" integer,
  "departament_id" integer,
  "role_id" integer,
  "uuid" uuid,
  "name" varchar(100),
  "personal_email" varchar(100),
  "corporation_email" int,
  "uf" varchar(2),
  "city" varchar(100),
  "tenure" varchar(50),
  "gender" varchar(10),
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "surveys" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" integer,
  "uuid" uuid,
  "name" varchar(100),
  "description" text,
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "survey_questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_id" integer,
  "uuid" uuid,
  "question" text,
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "survey_question_responses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_question_id" integer,
  "employee_id" integer,
  "uuid" uuid,
  "value" integer,
  "comment" text,
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

ALTER TABLE "employees" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("job_title_id") REFERENCES "job_titles" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("departament_id") REFERENCES "departaments" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "surveys" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "survey_questions" ADD FOREIGN KEY ("survey_id") REFERENCES "surveys" ("id");

ALTER TABLE "survey_question_responses" ADD FOREIGN KEY ("survey_question_id") REFERENCES "survey_questions" ("id");

ALTER TABLE "survey_question_responses" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
